### ISSUE TITLE
No model named segnet2?

### ISSUE THREAD

**Issue by d-li14** [bodokaiser/piwise#14]
Options for `args.model` just contains a "segnet" in `main.py`, but the `README.md#Usage` mentions command all with "segnet**2**"?

**Comment by bodokaiser** [comment]
main.py should be trusted. README is probably outdated.

**Comment by d-li14** [comment]
Thank you very much, but we would appreciate if you'd like to update the README to avoid other users 
 being confused.

**Comment by bodokaiser** [comment]
@d-li14 You can always send a PR. Best, Bodo

**Comment by sungwonida** [comment]
Oh, now it's clear for me that main.py should've been trusted than README.md. Thanks.
