### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by leemathew1998** [bodokaiser/piwise#15]
In the assessment there was a mistake, I was not familiar with image segmentation, the problem is here
RuntimeError: inconsistent tensor size, expected tensor [256 x 256] and mask [256] to have the same number of elements, but got 65536 and 256 elements respectively at d:\projects\pytorch\torch\lib\th\generic/THTensorMath.c:138
I feel that there is a problem here
        for label in range(1, len(self.cmap)):
            mask = gray_image[0] == label
            color_image[0][mask] = self.cmap[label][0]
            color_image[1][mask] = self.cmap[label][1]
            color_image[2][mask] = self.cmap[label][2]

**Comment by bodokaiser** [comment]
You probably have you images not as uint8 tensor type?

**Comment by leemathew1998** [comment]
In transform.py,
    def __call__(self, gray_image):
        size = gray_image.size()
        color_image = torch.ByteTensor(3, size[1], size[2]).fill_(0)

        for label in range(1, len(self.cmap)):
            mask = gray_image[0] == label

            color_image[0][mask] = self.cmap[label][0]
            color_image[1][mask] = self.cmap[label][1]
            color_image[2][mask] = self.cmap[label][2]
 I found size only two dimensions, like [256, 256],So I changed into size[0] and size[1], but the problem still exist

**Comment by dilligencer-zrj** [comment]
same question and expecting for solution

**Comment by bodokaiser** [comment]
> same question and expecting for solution

Please consider your attitude. This is a hobby project of mine which I open sourced to give the community some inspiration. I neither disclaim that it is complete nor that this is part of any commercial product or marketing strategy, hence you cannot expect me to do free consultant work for you.

Any help or support I provide is based on goodwill. Please appreciate this.  I previously pointed out a possible source for this error which however this was ignored. Furthermore I believe this issue to be problem dependent on your use case but still easy to with basic pytorch knowledge.

If you see your own time too valuable to fix this problem yourself we can discuss this as a consultant project. In this case please send me an email.
