### ISSUE TITLE
Does the relization of the Segnet in network.py match the paper of segnet?

### ISSUE THREAD

**Issue by mlx123** [bodokaiser/piwise#27]
Hello 
I read the  the relization of the Segnet in network.py and I have a question.
In the paper of Segnet,the last layer boxed in the picture below is (one Upsampling + one Conv +one Conv)
![default](https://user-images.githubusercontent.com/28173246/50697383-06a5db00-107d-11e9-92ca-5bba69f8a965.png)

but in the relization of the Segnet in network.py (https://github.com/bodokaiser/piwise/blob/50f8be658693dd27bfa463cb00d1acec7e869fc4/piwise/network.py#L275),the layer metioned above is (one Upsampling + one Conv)  ,it lose one Conv layer.
![default](https://user-images.githubusercontent.com/28173246/50697496-58e6fc00-107d-11e9-98bb-36c731734303.png)

Thank you

**Comment by bodokaiser** [comment]
So what is your question?

**Comment by bodokaiser** [comment]
Ah sry, did not see the email subject.

Q: Does the relization of the Segnet in network.py match the paper of segnet?
A: As you have noticed this seems not the case. I am not sure what impact this has on performance to be honest.
